import Head from 'next/head'
import {useState} from 'react'
import {tracks,moods} from '@/data/catalog'
import Icon from '@/components/offfreq/Icons'
import {TrackRow,SectionHeading,Label} from '@/components/offfreq/MusicUI'

export default function Search() {
  const [query,setQuery]=useState('')
  const [mood,setMood]=useState('All sounds')
  const results=tracks.filter(track=>(mood==='All sounds'||track.mood===mood) && [track.title,track.artist,track.album,track.genre,track.mood].join(' ').toLowerCase().includes(query.trim().toLowerCase()))
  return <><Head><title>Find your frequency — OFFFREQ</title><meta name="description" content="Discover music off the beaten path. Explore OFFFREQ's listening room."/></Head><div className="page-container sub-page"><div className="page-topline"><Label><span className="asterisk">✳</span> THE DIGGING STARTS HERE</Label><span className="issue-line">SEARCH / THE CATALOGUE</span></div><section className="sub-hero"><span className="micro-label">01 / THE SOUND FINDER</span><h1>Find your<br/><em>frequency.</em></h1><p>Artist on the tip of your tongue? A certain feeling you can&apos;t name? Start here.</p></section><div className="search-input-wrap"><Icon name="search" size={25}/><input autoComplete="off" autoFocus aria-label="Search music" placeholder="Try an artist, a feeling, a track..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} type="button" aria-label="Clear search"><Icon name="close" size={20}/></button>}<span>↵</span></div><div className="filter-section"><span className="micro-label">WHAT&apos;S THE MOOD?</span><div className="filter-row">{moods.map(item=><button type="button" key={item} className={`filter-pill ${mood===item?'filter-active':''}`} onClick={()=>setMood(item)} aria-pressed={mood===item}>{item}</button>)}</div></div><section className="search-results"><SectionHeading kicker={`02 / ${results.length} ${results.length===1?'RECORD':'RECORDS'} FOUND`} title={query?<>Here&apos;s what <em>turned up.</em></>:<>A little of <em>everything.</em></>}/>{results.length?<div className="results-list">{results.map((track,i)=><TrackRow key={track.id} track={track} index={i} list={results.map(item=>item.id)}/>)}</div>:<div className="empty-state"><span className="empty-asterisk">✳</span><h3>No tracks on this frequency.</h3><p>Try another artist, genre or feeling. The good stuff is out there.</p><button className="pill-cta" type="button" onClick={()=>{setQuery('');setMood('All sounds')}}>RESET SEARCH <Icon name="arrow" size={17}/></button></div>}</section><div className="site-signoff"><span>STAY CURIOUS. YOU&apos;RE IN GOOD COMPANY.</span><span>OFFFREQ / ISSUE 001</span></div></div></>
}
