import fs from 'node:fs'
import { tracks,mixes } from '../data/catalog.js'
const cover=(src)=>src.replace('/artwork/','./public/artwork/')
const icons = {discover:'✳',search:'⌕',grid:'⊞',heart:'♡',play:'▶',arrow:'↗'}
const rows=tracks.slice(4,9).map((track,i)=>`<div class="track-row"><div class="track-row-main"><span class="track-row-index">${String(i+1).padStart(2,'0')}</span><span class="row-cover-wrap"><img class="artwork" src="${cover(track.cover)}"></span><span class="row-track-names"><strong>${track.title}</strong><span>${track.artist}</span></span></div><span class="row-track-genre">${track.genre}</span><span class="row-track-time">${track.duration}</span><span class="save-button">♡</span></div>`).join('')
const cards=tracks.slice(0,4).map((track,i)=>`<article class="track-card"><div class="track-art-button"><img class="artwork" src="${cover(track.cover)}"/></div><div class="track-card-details"><div class="track-number">${String(i+1).padStart(2,'0')} / ${track.genre}</div><div class="track-card-title-row"><span class="track-title">${track.title}</span><span class="save-button save-compact">♡</span></div><span class="track-artist">${track.artist}</span></div></article>`).join('')
const mixCards=mixes.slice(0,2).map(mix=>`<article class="mix-card mix-card-wide"><div class="mix-card-visual"><img class="artwork" src="${cover(mix.cover)}"/><span class="mix-card-issue">OFFFREQ / MIX ${mix.index}</span></div><div class="mix-card-footer"><div><span class="mix-card-label">${mix.label}</span><h3>${mix.title}</h3><p>${mix.tagline}</p></div><div class="round-arrow dark">▶</div></div></article>`).join('')
const svgIcon=`<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><circle cx="10" cy="10" r="7"/><path d="M15 15 21 21"/></svg>`
const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OFFFREQ — visual direction preview</title><link rel="stylesheet" href="./styles/globals.css"/><link rel="icon" href="./public/favicon.svg"/></head><body><div class="app-shell">
<aside class="sidebar"><div class="sidebar-brand"><a class="brand"><span class="brand-glyph"><i></i><i></i><i></i><i></i></span><span class="brand-word">offfreq<span class="brand-period">.</span></span></a><div class="sidebar-brand-caption">GOOD MUSIC. NO SHORTCUTS.</div></div><div class="sidebar-section-label">THE LISTENING ROOM <span>01—04</span></div><nav class="primary-nav">${[['discover','Discover'],['search','Search'],['grid','The mixes'],['heart','Your shelf']].map(([icon,title],i)=>`<div class="nav-link ${i===0?'nav-link-active':''}"><span style="font-size:22px;width:20px;text-align:center">${icons[icon]}</span><span>${title}</span></div>`).join('')}</nav><div class="sidebar-divider"></div><div class="sidebar-section-label">ON THE DIAL <span>002</span></div><div class="sidebar-mixes">${mixes.slice(0,2).map(mix=>`<div class="sidebar-mix"><img class="artwork" src="${cover(mix.cover)}"/><span><strong>${mix.title}</strong><small>${mix.type.split(' / ')[0]}</small></span><span>↗</span></div>`).join('')}</div><div class="sidebar-bottom"><div class="sidebar-feature"><span class="feature-cross">✳</span><span class="sidebar-feature-title">LESS SKIPPING.<br/>MORE FEELING.</span><span class="sidebar-feature-bottom">MEET OFFFREQ <span>↗</span></span></div><div class="sidebar-footer"><span>EST. FOR THE LOVE OF IT</span><span>© 2026 / OF.</span></div></div></aside>
<div class="app-workspace"><header class="topbar"><div class="topbar-left"><span class="topbar-index">OF. / 001</span><span class="topbar-slash">/</span><span class="topbar-location">DISCOVER</span></div><div class="topbar-right"><span class="topbar-statement">AN INDEPENDENT CORNER OF THE INTERNET</span><span class="about-link">THE STORY ↗</span><span class="topbar-avatar">OF</span></div></header><main class="main-scroll"><div class="page-container home-page"><div class="page-topline"><span class="micro-label"><span class="asterisk">✳</span> WELCOME TO THE OTHER FREQUENCY</span><span class="issue-line">ISSUE 001 <span class="vertical-separator"></span> YOUR NEW LISTENING ROOM</span></div>
<section class="hero"><div class="hero-copy"><div class="hero-kicker"><span class="hero-kicker-bullet"></span> NOT ANOTHER PLAYLIST MACHINE.</div><h1>For ears<br/>that <em>wander.</em></h1><div class="hero-foot"><p>Deep cuts. Happy accidents. New favourites. A little corner of the internet for listening differently.</p><div class="hero-actions"><span class="pill-cta"><span class="cta-circle">▶</span> START LISTENING ↗</span><span class="text-link">WHAT IS OFFFREQ? →</span></div></div><div class="hero-serial">AN INDEPENDENT WAY TO PRESS PLAY. <span>↘</span></div></div>
<div class="hero-art"><div class="hero-art-top"><span>OFFFREQ SELECTS</span><span>VOL. 001 — 2026</span></div><div class="hero-art-main"><div class="hero-art-arc"></div><div class="hero-record"><div class="record-line record-line-1"></div><div class="record-line record-line-2"></div><div class="record-line record-line-3"></div><div class="record-label"><span>OF.</span><small>33⅓ RPM</small></div></div><div class="hero-art-star">✳</div><div class="hero-art-vertical">STAY CURIOUS · KEEP LISTENING</div></div><div class="hero-art-bottom"><div><span>ISSUE NO. 001</span><strong>SOUND<br/>WITHOUT<br/>THE NOISE.</strong></div><span class="hero-art-play">↗</span></div></div></section>
<div class="ticker"><div class="ticker-track"><span>FRESH FINDS</span><b>✳</b><span>NO ALGORITHMS. JUST GOOD EARS.</span><b>✳</b><span>A LITTLE OFF THE MAINSTREAM</span><b>✳</b><span>FRESH FINDS</span><b>✳</b><span>NO ALGORITHMS. JUST GOOD EARS.</span><b>✳</b></div></div>
<section class="section-block"><div class="section-heading"><div><span class="micro-label">01 / THE ROTATION</span><h2>Worth a <em>listen.</em></h2><p>Twelve tracks we'd happily put our name next to.</p></div><span class="inline-link">FIND MORE SOUNDS →</span></div><div class="track-grid">${cards}</div></section>
<section class="section-block featured-section"><div class="section-heading"><div><span class="micro-label">02 / CURATED WITH INTENTION</span><h2>Press play. <em>Go somewhere.</em></h2></div><span class="inline-link">ALL THE MIXES →</span></div><div class="featured-mixes">${mixCards}</div></section>
<section class="section-block recent-section"><div class="section-heading"><div><span class="micro-label">03 / LITTLE DISCOVERIES</span><h2>Still <em>digging.</em></h2></div></div><div class="recent-layout"><div class="recent-tracks">${rows}</div><div class="recent-note"><span class="recent-note-star">✳</span><span class="micro-label">A NOTE FROM THE EDITORS</span><h3>Less scrolling.<br/><em>More feeling.</em></h3><p>Everything here is picked on purpose. No endless feed. Just music with something to say.</p></div></div></section><div class="site-signoff"><span>GOOD MUSIC IS A GOOD PLACE TO START.</span><span>OFFFREQ STUDIO® 2026</span></div></div></main></div>
<footer class="player-dock"><div class="player-current"><img class="artwork" src="${cover(tracks[0].cover)}"/><div class="player-current-text"><span class="player-overline">NOW ON THE DIAL <span class="on-air"></span></span><strong>Almost Morning</strong><span>Luma Vale</span></div><span class="save-button">♡</span></div><div class="player-center"><div class="player-controls"><span class="player-side-control">⤨</span><span class="player-skip">◀◀</span><span class="player-play">▶</span><span class="player-skip">▶▶</span><span class="player-side-control">↻</span></div><div class="player-progress"><span>0:00</span><input aria-label="preview progression" type="range" value="0" min="0" max="100" style="--progress:0%"><span>3:42</span></div></div><div class="player-right"><span class="player-right-caption">SOUND GOOD?</span><span>☷</span><span>◖))</span><input class="player-volume" type="range" min="0" max="100" value="70" style="--progress:70%"><span class="player-volume-number">70</span></div></footer>
</div></body></html>`
fs.writeFileSync(new URL('../DESIGN_PREVIEW.html',import.meta.url),html)
console.log('Created DESIGN_PREVIEW.html with',tracks.length,'records')
